name: Deploy Database Infrastructure

env:
  TERRAFORM_VERSION: 1.5.7

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'develop'
        type: string

jobs:
  plan:
    name: Terraform Plan
    runs-on: codebuild-github-lncr-database-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init
      continue-on-error: false

    - name: Terraform Validate
      run: terraform validate
      continue-on-error: false

    - name: Terraform Plan
      run: terraform plan -var-file="prd.tfvars" -out=tfplan
      continue-on-error: false

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-database
        path: tfplan

  approve:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: plan
    # if: (github.ref == 'refs/heads/develop' && github.event_name == 'push') || github.event_name == 'repository_dispatch'

    
    steps:
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: gustavo-log, titoparizotto
        minimum-approvals: 1
        issue-title: "Deploy Database Infrastructure to Production"
        issue-body: "Please approve the deployment of database infrastructure changes to production environment."


  deploy:
    name: Terraform Deploy
    runs-on: codebuild-github-lncr-database-${{ github.run_id }}-${{ github.run_attempt }}

    needs: [plan, approve]
    # if: (github.ref == 'refs/heads/develop' && github.event_name == 'push') || github.event_name == 'repository_dispatch'


    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init
      continue-on-error: false

    - name: Download Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan-database

    - name: Terraform Apply
      run: terraform apply tfplan
      continue-on-error: false