name: Print Secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Save All Secrets to File
        env:
          DOCUMENTDB_PASSWORD : ${{ secrets.DOCUMENTDB_PASSWORD }}
          RDS_PASSWORD  : ${{ secrets.RDS_PASSWORD }}
          
        run: |
          cat > secrets.txt << EOF
          DOCUMENTDB_PASSWORD=$DOCUMENTDB_PASSWORD
          RDS_PASSWORD=$RDS_PASSWORD
          EOF
          echo "✅ Secrets saved to secrets.txt"

      - name: Upload Secrets as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-file
          path: secrets.txt
          retention-days: 1
